// IDs permanentes das Features -- nunca depender de string livre pro
// nome de uma Feature (o `feature` legível pode até mudar, o `id` nunca
// muda; quando o critério de uma Feature mudar de verdade, incrementa
// `version` no objeto da Feature, não o id).
module.exports = {
  FEATURE_FUNDING_EXTREME: "FEATURE_FUNDING_EXTREME",
  FEATURE_FUNDING_ACCELERATION: "FEATURE_FUNDING_ACCELERATION",
  FEATURE_VOLATILITY_EXPANSION: "FEATURE_VOLATILITY_EXPANSION",
  FEATURE_VOLATILITY_COMPRESSION: "FEATURE_VOLATILITY_COMPRESSION",
  FEATURE_VOLATILITY_PERSISTENCE: "FEATURE_VOLATILITY_PERSISTENCE",
  FEATURE_SPREAD_EXPANSION: "FEATURE_SPREAD_EXPANSION",
  FEATURE_OI_EXPANSION: "FEATURE_OI_EXPANSION",
  FEATURE_VOLUME_ANOMALY: "FEATURE_VOLUME_ANOMALY",
};
