CREATE TABLE asset (
  symbol TEXT PRIMARY KEY,
  asset_id TEXT,
  aliases TEXT,
  category TEXT,
  sub_category TEXT,
  sector TEXT,
  narrative TEXT,
  tags TEXT,
  supply TEXT,
  official_links TEXT,
  primary_exchange TEXT,
  contract_type TEXT,
  base_asset TEXT,
  quote_asset TEXT,
  status TEXT,
  relations TEXT,
  origin TEXT NOT NULL DEFAULT 'manual',
  confidence INTEGER,
  confidence_reason TEXT,
  confidence_source TEXT,
  last_verification TEXT,
  verification_method TEXT,
  version INTEGER NOT NULL DEFAULT 1,
  first_seen TEXT,
  last_seen TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
