CREATE TABLE asset_statistics_window (
  symbol TEXT NOT NULL,
  statistics_scope TEXT NOT NULL DEFAULT 'global',
  window_days INTEGER NOT NULL,
  window_candles INTEGER,
  coverage_pct REAL,
  freshness_score INTEGER,
  missing_rate REAL,
  duplicate_rate REAL,
  gap_rate REAL,
  sample_size INTEGER,
  effective_sample_size INTEGER,
  confidence INTEGER,
  version INTEGER NOT NULL DEFAULT 1,
  computed_at TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY (symbol, statistics_scope, window_days)
);

CREATE TABLE asset_metric_statistics (
  symbol TEXT NOT NULL,
  statistics_scope TEXT NOT NULL DEFAULT 'global',
  window_days INTEGER NOT NULL,
  metric TEXT NOT NULL,
  sample_size INTEGER,
  avg REAL,
  median REAL,
  stddev REAL,
  min REAL,
  max REAL,
  p10 REAL,
  p25 REAL,
  p50 REAL,
  p75 REAL,
  p90 REAL,
  p95 REAL,
  p99 REAL,
  mad REAL,
  iqr REAL,
  trimmed_mean REAL,
  winsorized_mean REAL,
  skewness REAL,
  kurtosis REAL,
  current_value REAL,
  zscore_current REAL,
  percentile_current REAL,
  drift_pct REAL,
  trend TEXT,
  velocity REAL,
  acceleration REAL,
  persistence INTEGER,
  compression_expansion TEXT,
  stability_score INTEGER,
  quality TEXT,
  confidence INTEGER,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY (symbol, statistics_scope, window_days, metric)
);
